name: Build customer portal deployment image

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Build Linux production image
        run: docker build --tag customer-portal:helios-${GITHUB_SHA} ./customer-portal
      - name: Save image
        run: docker save customer-portal:helios-${GITHUB_SHA} --output customer-portal-image.tar
      - uses: actions/upload-artifact@v4
        with:
          name: customer-portal-image
          path: customer-portal-image.tar
          retention-days: 1
